FROM registry.access.redhat.com/ubi8/ubi:latest as builder
RUN dnf install -y make git unzip gcc
RUN git clone https://github.com/wg/wrk.git --depth=1
RUN cd wrk && make -j $(nproc)

FROM registry.access.redhat.com/ubi8/ubi:latest
ARG VEGETA_VERSION
RUN dnf install -y iproute procps-ng
RUN curl -sS -L https://github.com/tsenart/vegeta/releases/download/v${VEGETA_VERSION}/vegeta_${VEGETA_VERSION}_linux_amd64.tar.gz | tar xz -C /usr/bin/
COPY --from=builder /wrk/wrk /usr/bin/wrk
COPY json.lua json.lua
