- termination: http
  connections: 100
  samples: 2
  duration: 1m
  path: /256.html
  concurrency: 25
  tool: wrk
  serverReplicas: 10
  tuningPatch: '{"spec":{"nodePlacement": {"nodeSelector": {"matchLabels": {"node-role.kubernetes.io/infra": ""}}}, "replicas": 2, "tuningOptions": {"threadCount": 16}}}'
- termination: reencrypt
  connections: 100
  duration: 1m
  path: /256.html
  concurrency: 25
  tool: wrk
  serverReplicas: 10
- termination: edge
  connections: 100
  samples: 2
  duration: 1m
  path: /256.html
  concurrency: 25
  tool: wrk
  serverReplicas: 10
  tuning:
- termination: passthrough
  connections: 100
  samples: 2
  duration: 1m
  path: /256.html
  concurrency: 25
  tool: wrk
  serverReplicas: 10
