# vim: expandtab shiftwidth=2 softtabstop=2

# First sample is set as warmup and also will tune the default ingress-controller to place the routers on infra nodes
- termination: http
  connections: 200
  samples: 2
  duration: 10s
  path: /1024.html
  concurrency: 3
  tool: hloader
  serverReplicas: 30
  delay: 5s
  procs: 1

- termination: edge
  connections: 200
  samples: 2
  duration: 10s
  path: /1024.html
  concurrency: 4
  tool: hloader
  serverReplicas: 30
  delay: 30s
  procs: 1

- termination: reencrypt
  connections: 200
  samples: 2
  duration: 30s
  path: /1024.html
  concurrency: 3
  tool: hloader
  serverReplicas: 30
  delay: 30s
  procs: 1

- termination: passthrough
  connections: 200
  samples: 2
  duration: 30s
  path: /1024.html
  concurrency: 3
  tool: hloader
  serverReplicas: 30
  delay: 30s
  procs: 1

- termination: http
  connections: 200
  samples: 2
  duration: 30s
  path: /1024.html
  concurrency: 3
  tool: hloader
  serverReplicas: 30
  delay: 30s

- termination: edge
  connections: 200
  samples: 2
  duration: 30s
  path: /1024.html
  concurrency: 3
  tool: hloader
  serverReplicas: 30
  delay: 30s

- termination: reencrypt
  connections: 200
  samples: 2
  duration: 30s
  path: /1024.html
  concurrency: 3
  tool: hloader
  serverReplicas: 30
  delay: 30s

- termination: passthrough
  connections: 200
  samples: 2
  duration: 30s
  path: /1024.html
  concurrency: 3
  tool: hloader
  serverReplicas: 30
  delay: 30s


